import React from 'react';

import {Text, View, StyleSheet} from 'react-native';

const ROW = (
    {
        row,
        rowr,
        wrap,
        flex,
        children,
        aligncenter,
        justifycenter,
        justifybetween,
        alignstart,
        alingend,
        justifyend,
        justifystart,
        pr,
        p,
        m,
        pl,
        pt,
        ph,
        pv,
        pb,
        mr,
        ml,
        mt,
        bc,
        mh,
        mv,
        mb,
        bg,
        bw,
        w,
        h,
        br,
        bbr,
        bbl,
        btr,
        btl,
        shadow,
        bottom,
        top,
        left,
        right,
        bs,
        style,
        justifyAround,
        alignSelf,
    },
    ...props
) => {
    return (
        <View
            {...props}
            style={[
                row && {flexDirection: 'row'},
                rowr && {flexDirection: 'row-reverse'},
                bg && {backgroundColor: bg},
                flex ? (flex > 1 ? {flex: flex} : {flex: 1}) : null,
                w && {width: w},
                br && {borderRadius: br},
                bbr && {borderBottomRightRadius: bbr},
                bbl && {borderBottomLeftRadius: bbl},
                btl && {borderTopLeftRadius: btl},
                btr && {borderTopRightRadius: btr},
                h && {height: h},
                p && {padding: p},
                pr && {paddingRight: pr},
                pl && {paddingLeft: pl},
                pt && {paddingTop: pt},
                pb && {paddingBottom: pb},
                ph && {paddingHorizontal: ph},
                pv && {paddingVertical: pv},
                m && {padding: m},
                mr && {marginRight: mr},
                bw && {borderWidth: bw},
                bs && {borderStyle: 'solid'},
                ml && {marginLeft: ml},
                mt && {marginTop: mt},
                mb && {marginBottom: mb},
                mh && {marginHorizontal: mh},
                mv && {marginVertical: mv},
                bw && {borderWidth: bw},
                bc && {borderColor: bc},
                left && {left: left},
                right && {right: right},
                top && {top: top},
                bottom && {bottom: bottom},
                wrap && {flexWrap: 'wrap'},
                aligncenter && {alignItems: 'center'},
                alignstart && {alignItems: 'flex-start'},
                alingend && {alignItems: 'flex-end'},
                justifycenter && {justifyContent: 'center'},
                justifystart && {justifyContent: 'flex-start'},
                justifyend && {justifyContent: 'flex-end'},
                justifybetween && {justifyContent: 'space-between'},
                justifyAround && {justifyContent: 'space-around'},
                alignSelf && {justifyContent: alignSelf},
                shadow && {
                    shadow: {
                        shadowOffset: {width: 0, height: 0},
                        shadowColor: 'black',
                        shadowOpacity: 1,
                        elevation: 12,
                        // background color must be set
                    },
                    shadowOffset: {width: 0, height: 0},
                    shadowColor: 'black',
                    shadowOpacity: 1,
                    elevation: 5,
                },
                style,
            ]}>
            {children}
        </View>
    );
};

export default React.memo(ROW);
